<!DOCTYPE html>
<html lang="da">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fabian Petersen - CV</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
            color: #333;
        }
        .container {
            display: flex;
            max-width: 1200px;
            margin: 20px auto;
            background: #fff;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        .sidebar {
            width: 30%;
            background-color: #2c3e50;
            color: white;
            padding: 20px;
            border-top-left-radius: 8px;
            border-bottom-left-radius: 8px;
        }
        .sidebar h1 {
            margin-top: 0;
        }
        .sidebar a {
            color: #1abc9c;
            text-decoration: none;
        }
        .sidebar a:hover {
            text-decoration: underline;
        }
        .content {
            width: 70%;
            padding: 20px;
        }
        .content h2 {
            border-bottom: 2px solid #1abc9c;
            padding-bottom: 5px;
            margin-bottom: 10px;
            color: #2c3e50;
        }
        .content ul {
            list-style: none;
            padding: 0;
        }
        .content ul li {
            margin-bottom: 10px;
        }
        .content p, .content ul li {
            line-height: 1.6;
        }
    </style>
</head>
<body>
    <div class="container">
        <!-- Sidebar -->
        <div class="sidebar">
            <h1>Fabian Petersen</h1>
            <p>Bøllingevej 25<br>6064 Jordrup</p>
            <p><strong>Mobil:</strong> 42544408</p>
            <p><strong>E-mail:</strong> <a href="mailto:fabianpetersern-@gmai.com">fabianpetersern-@gmai.com</a></p>
            <p><strong>LinkedIn:</strong><br>
                <a href="https://dk.linkedin.com/in/fabian-petersen-041944315/" target="_blank">Fabian Petersen</a>
            </p>
        </div>
        <!-- Main Content -->
        <div class="content">
            <section>
                <h2>Profil</h2>
                <p>Jeg har altid været vild med teknologi og hvordan forskellige komponenter hænger sammen. Jeg har valgt programmering som uddannelse og karriere, fordi jeg gerne vil være med til at stå bag softwareudvikling.</p>
                <p>Som person elsker jeg nye udfordringer og store projekter. Jeg er heller ikke bange for at samarbejde i grupper.</p>
            </section>
            <section>
                <h2>Uddannelse</h2>
                <ul>
                    <li>2024: Afgangseksamen, 9. klasse (gennemsnit 6,2)</li>
                    <li>2024: Starter på Syddansk Erhvervsskole (Odense)</li>
                </ul>
            </section>
            <section>
                <h2>Erfaring</h2>
                <p><strong>Folkeskoleprojekt, 9. klasse</strong></p>
                <ul>
                    <li>Emne: Cyber Security</li>
                    <li>Karakter: 10</li>
                </ul>
            </section>
            <section>
                <h2>IT-Færdigheder</h2>
                <ul>
                    <li>Microsoft Word, Excel og PowerPoint</li>
                    <li>Windows, Linux og macOS</li>
                    <li>Opsætning af diverse enheder som fx IP-kameraer og routere</li>
                    <li>Adobe Photoshop</li>
                </ul>
            </section>
            <section>
                <h2>Sprog</h2>
                <ul>
                    <li>Flydende i skrift og tale: Dansk</li>
                    <li>Samtaleniveau: Engelsk</li>
                </ul>
            </section>
            <section>
                <h2>Fritidsinteresser</h2>
                <ul>
                    <li>IT</li>
                    <li>Droner</li>
                    <li>DIY-projekter</li>
                    <li>Gaming</li>
                    <li>Fiskeri</li>
                    <li>At køre og reparere knallert</li>
                </ul>
            </section>
            <section>
                <h2>Referencer</h2>
                <p>Haves og gives efter aftale.</p>
            </section>
        </div>
    </div>
</body>
</html>
